### ISSUE TITLE
java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by mhktc** [jenkinsci/zulip-plugin#44]
Hello,

when we use the zulip notification plugin but on the end of a build we always get the following error message:
java.lang.ClassNotFoundException: org.apache.commons.httpclient.Credentials
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at jenkins.util.URLClassLoader2.findClass(URLClassLoader2.java:35)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
Caused: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/Credentials
	at jenkins.plugins.zulip.ZulipNotifier.publish(ZulipNotifier.java:133)
	at jenkins.plugins.zulip.ZulipNotifier.perform(ZulipNotifier.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
	at hudson.model.Build$BuildExecution.post2(Build.java:179)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
	at hudson.model.Run.execute(Run.java:1925)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)

I have already checked if the bot has sufficient permissions to send to a stream and verified it via curl, which works.
Our configuration is that the build-job, which atm. is just a job which tries to send a messages to a stream, is being executed on a jenkins node.
The node has the following java versions installed:
javac -version
javac 11.0.19

java -version
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

I already tried different bots  in different streams etc. but every job runs into the same error as stated above. In the documentation i couldnr find any hints about how to troubleshoot this error.

Maybe anyone here can help.

Regards

**Comment by jonesbusy** [comment]
Please provide list of plugins and version

https://www.jenkins.io/participate/report-issue/

But quick check is that you are probably not using latest version of the plugin which remove common http client:

https://github.com/jenkinsci/zulip-plugin/compare/1.3.0...2.0.0

**Comment by mhktc** [comment]
Hi,

thanks for the quick response.
Yes i was using the 1.3.0 version, ill try the latest but ill have to upgrade jenkins for that.

Regards
